sonar.projectKey=juangg11_Walter-Red-Social
sonar.organization=juangg11
sonar.host.url=https://sonarcloud.io

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Coverage
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Sources
sonar.sources=frontend/src,backend/src

# Tests
sonar.tests=frontend/src/__tests__,backend/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js

# Coverage thresholds
sonar.javascript.coverage.itRatio=100

# Coverage Exclusions
sonar.coverage.exclusions=backend/src/index.js,backend/src/config/db.js,backend/src/routes/**,backend/src/middleware/security.js,frontend/src/main.jsx,frontend/src/App.jsx,frontend/src/components/**,frontend/src/pages/**,frontend/src/assets/**

