steps:
  - uses: actions/checkout@v4

  - name: Analyze with SonarCloud
    uses: SonarSource/sonarcloud-github-action@master

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    with:
      args: >
        -Dsonar.projectKey=Walter-Red-Social
        -Dsonar.organization=juan-dev

      projectBaseDir: .
